name: Deploy Backend to AWS ECR

# Este workflow é acionado sempre que houver um push na branch 'main'
# E que as alterações ocorram dentro da pasta 'back-end/'
on:
  push:
    branches:
      - main
    paths:
      - 'back-end/**'

jobs:
  build-and-push-to-ecr:
    name: Build and Push to ECR
    runs-on: ubuntu-latest # Usa uma máquina virtual Linux para executar os passos

    steps:
      # 1. Copia o código do seu repositório para a máquina virtual
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Configura as credenciais da AWS usando os segredos que guardámos
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # IMPORTANTE: A sua região de Ohio

      # 3. Faz login no Amazon ECR (a nossa "garagem")
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 4. Constrói a imagem Docker e envia-a para o ECR
      - name: Build, tag, and push image to Amazon ECR
        env:
          # Substitua pelo ID da sua conta AWS e pelo nome do seu repositório ECR
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ecomanager-backend # O nome que deu ao seu repositório ECR
          IMAGE_TAG: ${{ github.sha }} # Usa o ID do commit como uma etiqueta de versão única
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./back-end
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG